version: "3"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: eiBarbeiro
    volumes:
      - /var/lib/postgresql/data

volumes:
  postgres_data:
